# Logging configuration
logging:
  level: "info"  # Possible values: debug, info, warn, error

# Metrics configuration
metrics:
  path: "/metrics"
  port: "9090"
  systemMetricsInterval: "10s"

# Router configuration
routerConfig:
  # Add any specific router configuration here if needed
  # For example:
  # timeout: "30s"
  # maxConnections: 100

# Server port for the EVM adapter proxy
serverPort: "3030"

# ICP configuration
icp:
  loggerCanisterId: "ydpfi-uiaaa-aaaal-qjupa-cai"
  dexCanisterId: "7eo5f-eqaaa-aaaam-adqoq-cai"
  nodeUrl: "https://ic0.app"  # Default IC mainnet URL
  timeout: "120s"  # Timeout for ICP operations
  disableSignedQueryVerification: true # Disable signed query verification for local testing
  fetchRootKey: false # Set true for mainnet

